SELECT name FROM Trainer WHERE hometown = 'Blue City';
SELECT name FROM Trainer WHERE hometown IN ('Brown City', 'Rainbow City');
SELECT name, hometown FROM Trainer WHERE name LIKE 'a%' OR name LIKE 'e%' OR name LIKE 'i%' OR name LIKE 'o%' OR name LIKE 'u%';
SELECT name FROM Pokemon WHERE type = 'Water';
SELECT DISTINCT type FROM Pokemon;
SELECT name FROM Pokemon ORDER BY name;
SELECT name FROM Pokemon WHERE name Like '%s';
SELECT name FROM Pokemon WHERE name LIKE '%e%s';
SELECT name FROM Pokemon WHERE name LIKE 'a%' OR name LIKE 'e%' OR name LIKE 'i%' OR name LIKE 'o%' OR name LIKE 'u%';
SELECT type, COUNT(*) AS 'C_type' FROM Pokemon GROUP BY type;
SELECT nickname FROM CatchedPokemon ORDER BY level DESC LIMIT 4;
SELECT AVG(level) FROM CatchedPokemon;
SELECT MAX(level) - MIN(level) AS 'Sub' FROM CatchedPokemon;
SELECT COUNT(*) AS N_Pokemon FROM Pokemon WHERE name LIKE 'b%' OR name LIKE 'c%' OR name LIKE 'd%' OR name LIKE 'e%';
SELECT COUNT(*) FROM Pokemon WHERE name NOT IN ('FIRE', 'Grass', 'Water', 'Electric');
SELECT T.name, P.name, nickname FROM CatchedPokemon AS C JOIN Trainer AS T ON T.id = C.owner_id JOIN Pokemon AS P ON P.id = C.pid WHERE nickname LIKE '% %';
SELECT T.name FROM Trainer AS T WHERE EXISTS (SELECT * FROM CatchedPokemon AS C WHERE C.owner_id = T.id AND C.pid IN (SELECT P.id FROM Pokemon AS P WHERE type = 'Psychic'));
SELECT T.name, T.hometown FROM Trainer AS T, CatchedPokemon AS C WHERE T.id = C.owner_id GROUP BY C.owner_id ORDER BY AVG(C.level) DESC LIMIT 3;
SELECT T.name, COUNT(C.pid) FROM Trainer AS T, CatchedPokemon AS C WHERE T.id = C.owner_id GROUP BY C.owner_id;
SELECT P.name, C.level FROM Gym AS G, Trainer AS T, CatchedPokemon AS C, Pokemon AS P WHERE G.city = 'Sangnok City' AND G.leader_id = T.id AND T.id = C.owner_id AND C.pid = P.id ORDER BY C.level;
SELECT P.name, COUNT(C.id) AS Catched FROM Pokemon AS P LEFT JOIN CatchedPokemon AS C ON P.id = C.pid GROUP BY P.id ORDER BY COUNT(C.id) DESC;
SELECT PO.name FROM Pokemon AS PO, Evolution AS E WHERE PO.id = E.after_id AND E.before_id IN (SELECT E.after_id FROM Pokemon AS P, Evolution AS E WHERE P.id = E.before_id AND P.name = 'Charmander');
SELECT DISTINCT name FROM Pokemon AS P, CatchedPokemon AS C WHERE P.id <= 30 AND C.pid = P.id ORDER BY P.name;
SELECT T.name, P.type FROM Trainer AS T, CatchedPokemon AS C, Pokemon AS P WHERE T.id = C.owner_id AND C.pid = P.id GROUP BY C.owner_id HAVING COUNT(DISTINCT P.type) < 2;
SELECT T.name, P.type, COUNT(P.type) FROM Trainer AS T, CatchedPokemon AS C, Pokemon AS P WHERE T.id = C.owner_id AND C.pid = P.id GROUP BY C.owner_id, P.type;
SELECT T.name, P.name, COUNT(DISTINCT P.name) AS Catched FROM Trainer AS T, CatchedPokemon AS C, Pokemon AS P WHERE T.id = C.owner_id AND C.pid = P.id GROUP BY C.owner_id HAVING COUNT(DISTINCT P.name) < 2;
SELECT TR.name, CY.name FROM Trainer AS TR, City AS CY, Gym AS G WHERE CY.name = G.city AND G.leader_id = TR.id AND TR.id in (SELECT CP.owner_id FROM CatchedPokemon AS CP, Pokemon AS P WHERE CP.pid = P.id GROUP BY CP.owner_id HAVING COUNT(DISTINCT P.type) >= 2);
SELECT T.name, SUM(IF(CP.level >= 50, CP.level, null)) AS SUM FROM Trainer AS T, CatchedPokemon AS CP, Gym AS G WHERE T.id = G.leader_id AND T.id = CP.owner_id GROUP BY T.id;
SELECT P.name FROM Pokemon AS P WHERE P.id IN (SELECT CP.pid FROM CatchedPokemon AS CP, Trainer AS T WHERE CP.owner_id = T.id AND T.hometown = 'Blue City') AND P.id IN (SELECT CP.pid FROM CatchedPokemon AS CP, Trainer AS T WHERE CP.owner_id = T.id AND T.hometown = 'Sangnok City');
SELECT P.name FROM Pokemon AS P WHERE P.id IN (SELECT E.after_id FROM Evolution AS E WHERE E.after_id NOT IN (SELECT V.before_id FROM Evolution AS V));
